name: 'coverage'
on:
    push:
        branches:
            - master
            - main
        paths:
            - Week 1/routes/**
    pull_request:
        branches:
            - master
            - main
        paths:
            - Week 1/api/**
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                working-directory: Week 1/routes
            - name: Install modules
              working-directory: Week 1/routes
              run: npm ci
            - name: Run ESLint
              working-directory: Week 1/routes
              run: npm run lint
