name: 'coverage'
on:
    push:
        branches:
            - master
            - main
        paths:
            - Week 1/api/**
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              with:
                working-directory: ./api
