name: 2 Chai/Mocha Tests

on:
  pull_request:
    branches:
      - development
      - master

env:
  NODE_VERSION: 18

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install test dependencies
        run: npm run pre-test

      - name: Code tests
        run: npm run test
